[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []
  included_files = ["node_modules/**"]

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  
[dev]
  command = "pnpm run dev"
  framework = "#custom"
  port = 5173
  targetPort = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200